# -*- coding: utf-8 -*-
"""Titanic_Analysis_AbuTalha_Saleem_F2024376221.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MxnGEpZfNRUjixC9_9UtOgDot2RLKD9h

# 🚢 Titanic Survival Analysis — Python AI Data Analysis Project

---

| | |
|---|---|
| **Project Title** | Titanic Survival Analysis: End-to-End Python AI Application |
| **Student Name** | AbuTalha Saleem |
| **Student ID** | F2024376221 |
| **Instructor** | Dr M. Wasim Nawaz |
| **Course** | Programming for AI (Python) — Semester Project |
| **Dataset** | [Titanic Dataset — Kaggle](https://www.kaggle.com/datasets/yasserh/titanic-dataset) |
| **Semester** | Fall 2026 |

---

## 📋 Project Overview
This project performs a **complete data-analysis pipeline** on the famous Titanic dataset.
It covers every mandatory deliverable:

1. ✅ **Data Collection & Loading** — download from Kaggle / bundled CSV  
2. ✅ **Data Preprocessing & Cleaning** — missing values, duplicates, type conversion, feature engineering  
3. ✅ **Exploratory Data Analysis (EDA)** — descriptive statistics, correlations  
4. ✅ **Data Visualization** — 8+ Matplotlib charts (bar, line, histogram, pie, scatter, heatmap)  
5. ✅ **Object-Oriented Programming** — 4 well-structured classes  
6. ✅ **GUI Application** — Tkinter interactive dashboard  
7. 🎁 **Bonus** — CSV export, search/filter, statistical summaries, correlation heatmap

## 1. 📦 Import Libraries
"""

# Standard & data libraries
import os
import io
import warnings
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
import matplotlib.ticker as mticker

# GUI
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

warnings.filterwarnings('ignore')
matplotlib.rcParams.update({
    'figure.facecolor': '#0d1117',
    'axes.facecolor':   '#161b22',
    'axes.edgecolor':   '#30363d',
    'axes.labelcolor':  '#e6edf3',
    'xtick.color':      '#e6edf3',
    'ytick.color':      '#e6edf3',
    'text.color':       '#e6edf3',
    'grid.color':       '#21262d',
    'grid.linestyle':   '--',
    'grid.alpha':       0.6,
    'legend.facecolor': '#161b22',
    'legend.edgecolor': '#30363d',
    'font.size':        11,
})

PALETTE = ['#58a6ff','#3fb950','#f78166','#d2a8ff','#ffa657','#79c0ff','#ff7b72','#56d364']
print("✅  All libraries imported successfully.")
print(f"   pandas  {pd.__version__} | numpy {np.__version__} | matplotlib {matplotlib.__version__}")

"""## 2. 📂 Data Collection & Loading"""

# ── Titanic dataset embedded as a reproducible CSV string (no internet needed) ──
# Full 891-row dataset as a downloadable CSV.
# If you have the Kaggle file, just replace the path below.

TITANIC_CSV_URL = (
    "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
)

try:
    df_raw = pd.read_csv(TITANIC_CSV_URL)
    print(f"✅  Loaded from URL — {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns")
except Exception:
    # Fallback: generate a representative synthetic sample so the notebook still runs offline
    np.random.seed(42)
    n = 891
    df_raw = pd.DataFrame({
        'PassengerId': range(1, n+1),
        'Survived':    np.random.choice([0,1], n, p=[0.62, 0.38]),
        'Pclass':      np.random.choice([1,2,3], n, p=[0.24, 0.21, 0.55]),
        'Name':        [f'Passenger_{i}' for i in range(1, n+1)],
        'Sex':         np.random.choice(['male','female'], n, p=[0.65, 0.35]),
        'Age':         np.where(np.random.rand(n)<0.2, np.nan, np.random.normal(29.7,14,n).clip(0.42,80)),
        'SibSp':       np.random.choice([0,1,2,3,4], n, p=[0.68,0.23,0.06,0.02,0.01]),
        'Parch':       np.random.choice([0,1,2,3],   n, p=[0.76,0.13,0.09,0.02]),
        'Ticket':      [f'TKT{i:04d}' for i in range(1, n+1)],
        'Fare':        np.where(np.random.rand(n)<0.01, np.nan, np.abs(np.random.lognormal(3.2, 1.1, n))),
        'Cabin':       np.where(np.random.rand(n)<0.77, np.nan, [f'C{i:03d}' for i in range(1, n+1)]),
        'Embarked':    np.where(np.random.rand(n)<0.02, np.nan,
                                np.random.choice(['S','C','Q'], n, p=[0.72,0.19,0.09])),
    })
    print(f"⚠️  URL unavailable — using synthetic Titanic data ({df_raw.shape[0]:,} rows)")

df_raw.head(5)

"""## 3. 🏗️ Object-Oriented Design

Four classes implement the full pipeline:

| Class | Responsibility |
|---|---|
| `DataLoader` | Load CSV from file path or URL; basic schema info |
| `DataPreprocessor` | Missing values, duplicates, type casting, feature engineering |
| `EDAAnalyzer` | Descriptive statistics, correlation matrix, group aggregations |
| `Visualizer` | All 8 Matplotlib charts with dark-theme styling |

"""

# ═══════════════════════════════════════════════════════════════════════════════
# CLASS 1 — DataLoader
# ═══════════════════════════════════════════════════════════════════════════════
class DataLoader:
    """Handles dataset ingestion from a local path or a URL."""

    def __init__(self, source: str):
        self.__source = source          # encapsulated attribute
        self._df = None

    # ── public methods ─────────────────────────────────────────────────────────
    def load(self) -> pd.DataFrame:
        """Load CSV and return a raw DataFrame."""
        self._df = pd.read_csv(self.__source)
        return self._df.copy()

    def schema_info(self) -> str:
        """Return a formatted schema summary string."""
        if self._df is None:
            raise RuntimeError("Call load() first.")
        buf = io.StringIO()
        self._df.info(buf=buf)
        return buf.getvalue()

    def head(self, n: int = 5) -> pd.DataFrame:
        return self._df.head(n)

    # ── property (encapsulation) ───────────────────────────────────────────────
    @property
    def source(self) -> str:
        return self.__source

    @property
    def shape(self):
        return self._df.shape if self._df is not None else None


# ═══════════════════════════════════════════════════════════════════════════════
# CLASS 2 — DataPreprocessor
# ═══════════════════════════════════════════════════════════════════════════════
class DataPreprocessor:
    """Clean and transform a raw Titanic DataFrame."""

    def __init__(self, df: pd.DataFrame):
        self._df = df.copy()
        self._steps_log = []              # audit trail of every step

    # ── public pipeline method ─────────────────────────────────────────────────
    def run_pipeline(self) -> pd.DataFrame:
        """Execute the full preprocessing pipeline and return a clean copy."""
        self._drop_irrelevant_columns()
        self._remove_duplicates()
        self._impute_age()
        self._impute_embarked()
        self._impute_fare()
        self._encode_sex()
        self._type_conversions()
        self._feature_engineering()
        self._filter_outliers()
        return self._df.copy()

    # ── private helpers ────────────────────────────────────────────────────────
    def _drop_irrelevant_columns(self):
        """Drop high-cardinality / ID columns that add no predictive value."""
        cols = [c for c in ['PassengerId','Name','Ticket','Cabin'] if c in self._df.columns]
        self._df.drop(columns=cols, inplace=True)
        self._log(f"Dropped columns: {cols}")

    def _remove_duplicates(self):
        before = len(self._df)
        self._df.drop_duplicates(inplace=True)
        self._log(f"Duplicates removed: {before - len(self._df)}")

    def _impute_age(self):
        """Fill missing Age with median stratified by Pclass & Sex."""
        missing_before = self._df['Age'].isna().sum()
        self._df['Age'] = self._df.groupby(['Pclass','Sex'])['Age'].transform(
            lambda x: x.fillna(x.median())
        )
        # fallback for any remaining
        self._df['Age'].fillna(self._df['Age'].median(), inplace=True)
        self._log(f"Age — imputed {missing_before} missing values (stratified median)")

    def _impute_embarked(self):
        missing = self._df['Embarked'].isna().sum()
        mode_val = self._df['Embarked'].mode()[0]
        self._df['Embarked'].fillna(mode_val, inplace=True)
        self._log(f"Embarked — filled {missing} NaN with mode '{mode_val}'")

    def _impute_fare(self):
        missing = self._df['Fare'].isna().sum()
        if missing:
            self._df['Fare'].fillna(self._df['Fare'].median(), inplace=True)
            self._log(f"Fare — filled {missing} NaN with median")

    def _encode_sex(self):
        """One-hot encode Sex; keep original for EDA."""
        self._df['Sex_Code'] = (self._df['Sex'] == 'female').astype(int)
        self._log("Sex_Code column created (female=1, male=0)")

    def _type_conversions(self):
        self._df['Pclass']   = self._df['Pclass'].astype('category')
        self._df['Survived'] = self._df['Survived'].astype(int)
        self._df['Age']      = self._df['Age'].round(1)
        self._log("Data types cast: Pclass→category, Survived→int, Age→float(1dp)")

    def _feature_engineering(self):
        """Add domain-derived features."""
        self._df['FamilySize']  = self._df['SibSp'] + self._df['Parch'] + 1
        self._df['IsAlone']     = (self._df['FamilySize'] == 1).astype(int)
        self._df['FarePerPerson'] = (self._df['Fare'] / self._df['FamilySize']).round(2)
        self._df['AgeGroup']    = pd.cut(
            self._df['Age'],
            bins=[0, 12, 18, 35, 60, 100],
            labels=['Child','Teen','YoungAdult','Adult','Senior']
        )
        self._log("Feature engineering: FamilySize, IsAlone, FarePerPerson, AgeGroup")

    def _filter_outliers(self):
        """Cap Fare at 99th percentile to reduce skew."""
        cap = self._df['Fare'].quantile(0.99)
        outliers = (self._df['Fare'] > cap).sum()
        self._df['Fare'] = self._df['Fare'].clip(upper=cap)
        self._log(f"Fare outliers capped at 99th-percentile ({cap:.2f}): {outliers} rows affected")

    def _log(self, msg: str):
        self._steps_log.append(msg)

    # ── property ───────────────────────────────────────────────────────────────
    @property
    def pipeline_log(self):
        return self._steps_log


# ═══════════════════════════════════════════════════════════════════════════════
# CLASS 3 — EDAAnalyzer
# ═══════════════════════════════════════════════════════════════════════════════
class EDAAnalyzer:
    """Compute descriptive statistics and aggregations on the clean DataFrame."""

    def __init__(self, df: pd.DataFrame):
        self._df = df.copy()

    def describe(self) -> pd.DataFrame:
        return self._df.describe(include='all').T

    def missing_report(self) -> pd.DataFrame:
        miss  = self._df.isna().sum()
        pct   = (miss / len(self._df) * 100).round(2)
        return pd.DataFrame({'Missing': miss, 'Pct (%)': pct}).query('Missing > 0')

    def survival_rate(self, groupby_col: str) -> pd.DataFrame:
        grp = self._df.groupby(groupby_col)['Survived']
        return pd.DataFrame({
            'Total':    grp.count(),
            'Survived': grp.sum(),
            'Rate (%)': (grp.mean() * 100).round(1)
        })

    def correlation_matrix(self) -> pd.DataFrame:
        num = self._df.select_dtypes(include=[np.number])
        return num.corr()

    def age_stats(self) -> dict:
        a = self._df['Age']
        return {'mean': a.mean(), 'median': a.median(),
                'std': a.std(), 'min': a.min(), 'max': a.max()}

    def fare_stats(self) -> dict:
        f = self._df['Fare']
        return {'mean': f.mean(), 'median': f.median(),
                'std': f.std(), 'min': f.min(), 'max': f.max()}


# ═══════════════════════════════════════════════════════════════════════════════
# CLASS 4 — Visualizer
# ═══════════════════════════════════════════════════════════════════════════════
class Visualizer:
    """Generate all publication-quality Matplotlib charts."""

    def __init__(self, df: pd.DataFrame, eda: EDAAnalyzer):
        self._df  = df.copy()
        self._eda = eda

    # ── Chart helpers ──────────────────────────────────────────────────────────
    @staticmethod
    def _style_ax(ax, title, xlabel='', ylabel=''):
        ax.set_title(title, fontsize=13, fontweight='bold', pad=10)
        ax.set_xlabel(xlabel)
        ax.set_ylabel(ylabel)
        ax.grid(axis='y', alpha=0.4)
        for spine in ax.spines.values():
            spine.set_visible(False)

    # ── 1. Bar Chart — Survival by Pclass ─────────────────────────────────────
    def plot_survival_by_class(self, ax=None):
        standalone = ax is None
        if standalone: fig, ax = plt.subplots(figsize=(7, 4.5))
        sr = self._eda.survival_rate('Pclass')
        x  = np.arange(len(sr))
        w  = 0.35
        ax.bar(x-w/2, sr['Total'],    w, label='Total',    color=PALETTE[0], alpha=0.9)
        ax.bar(x+w/2, sr['Survived'], w, label='Survived', color=PALETTE[1], alpha=0.9)
        ax.set_xticks(x)
        ax.set_xticklabels([f'Class {c}' for c in sr.index])
        for i,(tot,sur) in enumerate(zip(sr['Total'],sr['Survived'])):
            ax.text(i-w/2, tot+3,  str(tot), ha='center', fontsize=9)
            ax.text(i+w/2, sur+3,  str(sur), ha='center', fontsize=9)
        ax.legend()
        self._style_ax(ax,'Survival Count by Passenger Class','Pclass','Count')
        if standalone: plt.tight_layout(); plt.show()

    # ── 2. Pie Chart — Overall Survival ───────────────────────────────────────
    def plot_survival_pie(self, ax=None):
        standalone = ax is None
        if standalone: fig, ax = plt.subplots(figsize=(5, 5))
        vals   = self._df['Survived'].value_counts()
        labels = ['Did Not Survive', 'Survived']
        colors = [PALETTE[2], PALETTE[1]]
        wedge_props = {'linewidth': 2, 'edgecolor': '#0d1117'}
        ax.pie(vals, labels=labels, colors=colors, autopct='%1.1f%%',
               startangle=140, wedgeprops=wedge_props,
               textprops={'color':'#e6edf3','fontsize':11})
        ax.set_title('Overall Survival Rate', fontsize=13, fontweight='bold')
        if standalone: plt.tight_layout(); plt.show()

    # ── 3. Histogram — Age Distribution ───────────────────────────────────────
    def plot_age_histogram(self, ax=None):
        standalone = ax is None
        if standalone: fig, ax = plt.subplots(figsize=(7, 4.5))
        survived   = self._df[self._df['Survived']==1]['Age']
        not_surv   = self._df[self._df['Survived']==0]['Age']
        ax.hist(not_surv, bins=30, alpha=0.7, color=PALETTE[2], label='Did Not Survive')
        ax.hist(survived, bins=30, alpha=0.7, color=PALETTE[1], label='Survived')
        ax.axvline(self._df['Age'].median(), color='yellow', linestyle='--',
                   linewidth=1.5, label=f'Median Age {self._df["Age"].median():.1f}')
        ax.legend()
        self._style_ax(ax,'Age Distribution by Survival Outcome','Age','Frequency')
        if standalone: plt.tight_layout(); plt.show()

    # ── 4. Bar Chart — Survival Rate by Sex ───────────────────────────────────
    def plot_survival_by_sex(self, ax=None):
        standalone = ax is None
        if standalone: fig, ax = plt.subplots(figsize=(6, 4.5))
        sr   = self._eda.survival_rate('Sex')
        cols = [PALETTE[0], PALETTE[3]]
        bars = ax.bar(sr.index, sr['Rate (%)'], color=cols, alpha=0.9, width=0.4)
        for b,v in zip(bars, sr['Rate (%)']):
            ax.text(b.get_x()+b.get_width()/2, v+1, f'{v}%', ha='center', fontweight='bold')
        self._style_ax(ax,'Survival Rate by Sex (%)','Sex','Survival Rate (%)')
        if standalone: plt.tight_layout(); plt.show()

    # ── 5. Scatter Plot — Age vs Fare (coloured by Survival) ──────────────────
    def plot_age_vs_fare(self, ax=None):
        standalone = ax is None
        if standalone: fig, ax = plt.subplots(figsize=(8, 5))
        for survived, color, label in [(0, PALETTE[2], 'Did Not Survive'),
                                        (1, PALETTE[1], 'Survived')]:
            sub = self._df[self._df['Survived'] == survived]
            ax.scatter(sub['Age'], sub['Fare'], alpha=0.45, s=25,
                       color=color, label=label)
        ax.legend()
        self._style_ax(ax,'Age vs Fare coloured by Survival','Age','Fare (£)')
        if standalone: plt.tight_layout(); plt.show()

    # ── 6. Line Chart — Average Fare Trend by Age Group ──────────────────────
    def plot_fare_trend_by_age_group(self, ax=None):
        standalone = ax is None
        if standalone: fig, ax = plt.subplots(figsize=(7, 4.5))
        trend = self._df.groupby('AgeGroup', observed=True)['Fare'].mean()
        ax.plot(trend.index.astype(str), trend.values, marker='o',
                color=PALETTE[4], linewidth=2.2, markersize=7)
        for x, y in zip(trend.index.astype(str), trend.values):
            ax.text(x, y + 0.5, f'£{y:.1f}', ha='center', fontsize=9)
        self._style_ax(ax,'Average Fare by Age Group','Age Group','Avg Fare (£)')
        if standalone: plt.tight_layout(); plt.show()

    # ── 7. Heatmap — Correlation Matrix (Bonus) ───────────────────────────────
    def plot_correlation_heatmap(self, ax=None):
        standalone = ax is None
        if standalone: fig, ax = plt.subplots(figsize=(8, 6))
        corr = self._eda.correlation_matrix()
        im   = ax.imshow(corr, cmap='coolwarm', vmin=-1, vmax=1)
        ax.set_xticks(range(len(corr))); ax.set_yticks(range(len(corr)))
        ax.set_xticklabels(corr.columns, rotation=45, ha='right', fontsize=8)
        ax.set_yticklabels(corr.columns, fontsize=8)
        for i in range(len(corr)):
            for j in range(len(corr)):
                ax.text(j, i, f'{corr.iloc[i,j]:.2f}',
                        ha='center', va='center', fontsize=7,
                        color='white' if abs(corr.iloc[i,j]) > 0.5 else '#e6edf3')
        plt.colorbar(im, ax=ax, shrink=0.8)
        ax.set_title('Feature Correlation Heatmap', fontsize=13, fontweight='bold')
        if standalone: plt.tight_layout(); plt.show()

    # ── 8. Stacked Bar — Survival by AgeGroup & Pclass ────────────────────────
    def plot_survival_by_agegroup(self, ax=None):
        standalone = ax is None
        if standalone: fig, ax = plt.subplots(figsize=(8, 5))
        pivot = self._df.pivot_table(index='AgeGroup', columns='Survived',
                                     values='PassengerId' if 'PassengerId' in self._df.columns
                                     else 'FamilySize',
                                     aggfunc='count', observed=True).fillna(0)
        # fallback: use value_counts approach
        grp = self._df.groupby(['AgeGroup','Survived'], observed=True).size().unstack(fill_value=0)
        x   = np.arange(len(grp))
        ax.bar(x, grp[0], color=PALETTE[2], alpha=0.9, label='Did Not Survive')
        ax.bar(x, grp[1], bottom=grp[0], color=PALETTE[1], alpha=0.9, label='Survived')
        ax.set_xticks(x); ax.set_xticklabels(grp.index.astype(str), rotation=20)
        ax.legend()
        self._style_ax(ax,'Survival Count by Age Group (Stacked)','Age Group','Count')
        if standalone: plt.tight_layout(); plt.show()

print("✅  All 4 OOP classes defined successfully.")
print("   DataLoader | DataPreprocessor | EDAAnalyzer | Visualizer")

"""## 4. ⚙️ Run the Full Data Pipeline"""

# ── Step 1: Load ──────────────────────────────────────────────────────────────
loader = DataLoader(TITANIC_CSV_URL)
try:
    df_raw = loader.load()
except Exception:
    pass   # df_raw already set above

print("=== RAW DATASET ===")
print(f"Shape : {df_raw.shape}")
print(f"Columns: {list(df_raw.columns)}")
df_raw.head(3)

# ── Step 2: Preprocess ────────────────────────────────────────────────────────
preprocessor = DataPreprocessor(df_raw)
df_clean = preprocessor.run_pipeline()

print("=== PREPROCESSING LOG ===")
for i, step in enumerate(preprocessor.pipeline_log, 1):
    print(f"  {i:02d}. {step}")

print(f"\n=== CLEAN DATASET ===")
print(f"Shape : {df_clean.shape}")
print(f"Columns: {list(df_clean.columns)}")
df_clean.head(3)

"""## 5. 🔍 Exploratory Data Analysis (EDA)"""

eda = EDAAnalyzer(df_clean)

print("=== DESCRIPTIVE STATISTICS ===")
display(eda.describe())

print("=== MISSING VALUES AFTER PREPROCESSING ===")
miss = eda.missing_report()
if miss.empty:
    print("  ✅  No missing values remain.")
else:
    display(miss)

print("\n=== SURVIVAL RATE BY PASSENGER CLASS ===")
display(eda.survival_rate('Pclass'))

print("\n=== SURVIVAL RATE BY SEX ===")
display(eda.survival_rate('Sex'))

print("\n=== SURVIVAL RATE BY AGE GROUP ===")
display(eda.survival_rate('AgeGroup'))

print("\n=== AGE STATISTICS ===")
for k,v in eda.age_stats().items():
    print(f"  {k:8s}: {v:.2f}")

print("\n=== FARE STATISTICS ===")
for k,v in eda.fare_stats().items():
    print(f"  {k:8s}: {v:.2f}")

"""## 6. 📊 Data Visualizations

Eight distinct chart types are produced below — all rendered in a cohesive dark theme.

"""

viz = Visualizer(df_clean, eda)

# ── Visualization 1: Survival by Class (Bar Chart) ────────────────────────────
print("Chart 1 — Bar Chart: Survival Count by Passenger Class")
viz.plot_survival_by_class()

# ── Visualization 2: Overall Survival (Pie Chart) ─────────────────────────────
print("Chart 2 — Pie Chart: Overall Survival Rate")
viz.plot_survival_pie()

# ── Visualization 3: Age Distribution (Histogram) ────────────────────────────
print("Chart 3 — Histogram: Age Distribution by Survival Outcome")
viz.plot_age_histogram()

# ── Visualization 4: Survival Rate by Sex (Bar Chart) ─────────────────────────
print("Chart 4 — Bar Chart: Survival Rate by Sex")
viz.plot_survival_by_sex()

# ── Visualization 5: Age vs Fare (Scatter Plot) ───────────────────────────────
print("Chart 5 — Scatter Plot: Age vs Fare coloured by Survival")
viz.plot_age_vs_fare()

# ── Visualization 6: Average Fare Trend by Age Group (Line Chart) ─────────────
print("Chart 6 — Line Chart: Average Fare Trend by Age Group")
viz.plot_fare_trend_by_age_group()

# ── Visualization 7: Correlation Heatmap (Bonus) ─────────────────────────────
print("Chart 7 — Heatmap: Feature Correlation Matrix (Bonus Feature)")
viz.plot_correlation_heatmap()

# ── Visualization 8: Stacked Bar — Survival by Age Group ─────────────────────
print("Chart 8 — Stacked Bar: Survival Count by Age Group")
viz.plot_survival_by_agegroup()

"""## 7. 🖼️ Master Dashboard — All Charts at a Glance"""

fig = plt.figure(figsize=(22, 26))
fig.suptitle('🚢 Titanic Dataset — Complete Analysis Dashboard\nAbuTalha Saleem | F2024376221',
             fontsize=16, fontweight='bold', color='#e6edf3', y=0.98)

gs = GridSpec(4, 2, figure=fig, hspace=0.55, wspace=0.35)
axes = [
    fig.add_subplot(gs[0, 0]),
    fig.add_subplot(gs[0, 1]),
    fig.add_subplot(gs[1, 0]),
    fig.add_subplot(gs[1, 1]),
    fig.add_subplot(gs[2, 0]),
    fig.add_subplot(gs[2, 1]),
    fig.add_subplot(gs[3, 0]),
    fig.add_subplot(gs[3, 1]),
]

viz.plot_survival_by_class(axes[0])
viz.plot_survival_pie(axes[1])
viz.plot_age_histogram(axes[2])
viz.plot_survival_by_sex(axes[3])
viz.plot_age_vs_fare(axes[4])
viz.plot_fare_trend_by_age_group(axes[5])
viz.plot_correlation_heatmap(axes[6])
viz.plot_survival_by_agegroup(axes[7])

plt.savefig('/tmp/titanic_dashboard.png', dpi=150, bbox_inches='tight',
            facecolor='#0d1117')
plt.show()
print("✅  Dashboard saved to /tmp/titanic_dashboard.png")

"""## 8. 💾 Bonus — CSV Export & Statistical Summary"""

# Export clean dataset
export_path = '/tmp/titanic_clean.csv'
df_clean.to_csv(export_path, index=False)
print(f"✅  Clean dataset exported → {export_path}")
print(f"   Rows: {len(df_clean):,} | Columns: {len(df_clean.columns)}")

# Detailed statistical summary grouped by Pclass
print("\n=== GROUP STATISTICS BY PCLASS ===")
summary = df_clean.groupby('Pclass', observed=True).agg(
    Passengers=('Survived','count'),
    Survivors=('Survived','sum'),
    SurvivalRate=('Survived','mean'),
    AvgAge=('Age','mean'),
    AvgFare=('Fare','mean'),
    AvgFamilySize=('FamilySize','mean')
).round(2)
summary['SurvivalRate'] = (summary['SurvivalRate']*100).round(1).astype(str) + '%'
display(summary)

# Correlation with Survived
print("\n=== TOP CORRELATIONS WITH SURVIVAL ===")
corr_surv = df_clean.select_dtypes(include=np.number).corr()['Survived'].drop('Survived').abs().sort_values(ascending=False)
display(corr_surv.rename('|Correlation with Survived|').to_frame())

"""## 9. 🖥️ GUI Application — Tkinter Interactive Dashboard

The cell below launches a full **Tkinter desktop app** with:
- Load Dataset button  
- Dataset Summary panel  
- 8 chart selectors (dropdown)  
- Live chart rendering inside the window  
- Search / Filter by Sex & Pclass  
- Export filtered CSV  

> **Note:** The GUI requires a display (run locally on your machine or in a Jupyter environment with `%matplotlib tk`). In a headless cloud environment the cell will gracefully print a message and skip the launch.

"""

import sys

# ─── TitanicGUI class ────────────────────────────────────────────────────────
class TitanicGUI:
    """
    Tkinter-based interactive GUI for Titanic analysis.
    Provides dataset loading, summary view, chart selection,
    search/filter, and CSV export.
    """

    CHARTS = [
        "1. Survival Count by Passenger Class (Bar)",
        "2. Overall Survival Rate (Pie)",
        "3. Age Distribution by Survival (Histogram)",
        "4. Survival Rate by Sex (Bar)",
        "5. Age vs Fare by Survival (Scatter)",
        "6. Avg Fare Trend by Age Group (Line)",
        "7. Feature Correlation Heatmap",
        "8. Survival Count by Age Group (Stacked Bar)",
    ]

    BG      = "#0d1117"
    BG2     = "#161b22"
    ACCENT  = "#58a6ff"
    FG      = "#e6edf3"
    GREEN   = "#3fb950"
    RED   = "#f78166"

    def __init__(self, root: tk.Tk, df: pd.DataFrame):
        self._root = root
        self._df   = df.copy()
        self._filtered_df = df.copy()
        self._build_ui()

    # ── UI construction ───────────────────────────────────────────────────────
    def _build_ui(self):
        r = self._root
        r.title("🚢  Titanic Analysis Dashboard — AbuTalha Saleem")
        r.configure(bg=self.BG)
        r.geometry("1300x820")
        r.resizable(True, True)

        # ── Header ────────────────────────────────────────────────────────────
        hdr = tk.Frame(r, bg=self.BG2, pady=8)
        hdr.pack(fill='x')
        tk.Label(hdr, text="🚢  Titanic Survival Analysis",
                 font=("Helvetica",18,"bold"), bg=self.BG2,
                 fg=self.ACCENT).pack(side='left', padx=20)
        tk.Label(hdr, text="AbuTalha Saleem | F2024376221 | Dr M. Wasim Nawaz",
                 font=("Helvetica",10), bg=self.BG2, fg=self.FG).pack(side='right', padx=20)

        # ── Control panel (left) ──────────────────────────────────────────────
        ctrl = tk.Frame(r, bg=self.BG2, width=280, padx=12, pady=12)
        ctrl.pack(side='left', fill='y')
        ctrl.pack_propagate(False)

        self._btn(ctrl, "📂  Load Dataset", self._load_dataset).pack(fill='x', pady=4)
        self._btn(ctrl, "📋  Show Summary",  self._show_summary).pack(fill='x', pady=4)

        ttk.Separator(ctrl, orient='horizontal').pack(fill='x', pady=8)
        tk.Label(ctrl, text="Select Chart:", bg=self.BG2, fg=self.FG,
                 font=("Helvetica",11,"bold")).pack(anchor='w')

        self._chart_var = tk.StringVar(value=self.CHARTS[0])
        chart_menu = ttk.Combobox(ctrl, textvariable=self._chart_var,
                                  values=self.CHARTS, state='readonly', width=32)
        chart_menu.pack(fill='x', pady=4)
        self._btn(ctrl, "📊  Render Chart", self._render_chart).pack(fill='x', pady=4)

        ttk.Separator(ctrl, orient='horizontal').pack(fill='x', pady=8)
        tk.Label(ctrl, text="ðŸ’„ Search & Filter:", bg=self.BG2, fg=self.FG,
                 font=("Helvetica",11,"bold")).pack(anchor='w')

        tk.Label(ctrl, text="Sex:", bg=self.BG2, fg=self.FG).pack(anchor='w')
        self._sex_var = tk.StringVar(value='All')
        ttk.Combobox(ctrl, textvariable=self._sex_var,
                     values=['All','male','female'], state='readonly',
                     width=15).pack(anchor='w', pady=2)

        tk.Label(ctrl, text="Pclass:", bg=self.BG2, fg=self.FG).pack(anchor='w')
        self._pclass_var = tk.StringVar(value='All')
        ttk.Combobox(ctrl, textvariable=self._pclass_var,
                     values=['All','1','2','3'], state='readonly',
                     width=15).pack(anchor='w', pady=2)

        self._btn(ctrl, "ðŸ’„  Apply Filter",   self._apply_filter).pack(fill='x', pady=4)
        self._btn(ctrl, "â‍↶️  Reset Filter",   self._reset_filter).pack(fill='x', pady=2)
        self._btn(ctrl, "ðŸ’‚  Export CSV",     self._export_csv,
                  bg=self.GREEN).pack(fill='x', pady=10)

        self._status = tk.StringVar(value="Ready — load a dataset to begin.")
        tk.Label(ctrl, textvariable=self._status, bg=self.BG2, fg=self.ACCENT,
                 wraplength=255, justify='left',
                 font=("Helvetica",9)).pack(anchor='w', pady=8)

        # ── Main area (right) ─────────────────────────────────────────────────
        main = tk.Frame(r, bg=self.BG)
        main.pack(side='right', fill='both', expand=True, padx=8, pady=8)

        # Summary text
        self._summary_frame = tk.Frame(main, bg=self.BG2)
        self._summary_text  = tk.Text(self._summary_frame, bg=self.BG2, fg=self.FG,
                                      font=("Courier",9), wrap='none',
                                      height=10, relief='flat', bd=0)
        sb = ttk.Scrollbar(self._summary_frame, command=self._summary_text.yview)
        self._summary_text.configure(yscrollcommand=sb.set)
        sb.pack(side='right', fill='y')
        self._summary_text.pack(fill='both', expand=True)

        # Chart canvas
        self._chart_frame = tk.Frame(main, bg=self.BG)
        self._canvas_widget = None

        self._summary_frame.pack(fill='both', expand=True)
        self._chart_frame.pack(fill='both', expand=True)

        # Preload data
        self._eda = EDAAnalyzer(self._df)
        self._viz = Visualizer(self._df, self._eda)
        self._status.set(f"✅  Data ready — {len(self._df):,} passengers loaded.")

    # ── Helpers ───────────────────────────────────────────────────────────────
    def _btn(self, parent, text, cmd, bg=None):
        return tk.Button(parent, text=text, command=cmd, relief='flat',
                         bg=bg or self.ACCENT, fg='#0d1117',
                         font=("Helvetica",10,"bold"), padx=6, pady=5,
                         cursor='hand2', activebackground='#1f6feb')

    def _load_dataset(self):
        path = filedialog.askopenfilename(filetypes=[("CSV files","*.csv")])
        if path:
            try:
                self._df = pd.read_csv(path)
                prep = DataPreprocessor(self._df)
                self._df = prep.run_pipeline()
                self._filtered_df = self._df.copy()
                self._eda = EDAAnalyzer(self._df)
                self._viz = Visualizer(self._df, self._eda)
                self._status.set(f"✅  Loaded: {path.split('/')[-1]}\n{len(self._df):,} rows")
            except Exception as e:
                messagebox.showerror("Load Error", str(e))

    def _show_summary(self):
        self._chart_frame.pack_forget()
        self._summary_frame.pack(fill='both', expand=True)
        self._summary_text.config(state='normal')
        self._summary_text.delete('1.0','end')

        lines = ["=" * 60, "  DATASET SUMMARY", "=" * 60]
        lines += [f"  Rows     : {len(self._df):,}",
                  f"  Columns  : {len(self._df.columns)}",
                  f"  Survivors: {self._df['Survived'].sum()} "
                  f"({self._df['Survived'].mean()*100:.1f}%)", ""]
        lines += ["  SURVIVAL BY CLASS:", "-" * 40]
        sr = self._eda.survival_rate('Pclass')
        for idx, row in sr.iterrows():
            lines.append(f"  Class {idx}: {row['Survived']}/{row['Total']} "
                         f"({row['Rate (%)']}%)")
        lines += ["", "  SURVIVAL BY SEX:", "-" * 40]
        sr2 = self._eda.survival_rate('Sex')
        for idx, row in sr2.iterrows():
            lines.append(f"  {idx:6s}: {row['Survived']}/{row['Total']} "
                         f"({row['Rate (%)']}%)!")
        lines += ["", "  AGE STATS:", "-" * 40]
        for k,v in self._eda.age_stats().items():
            lines.append(f"  {k:8s}: {v:.2f}")
        lines += ["", "  FARE STATS:", "-" * 40]
        for k,v in self._eda.fare_stats().items():
            lines.append(f"  {k:8s}: {v:.2f}")

        content = chr(10).join(lines)          # chr(10) = newline, no literal \n needed
        self._summary_text.insert('end', content)
        self._summary_text.config(state='disabled')

    def _render_chart(self):
        self._summary_frame.pack_forget()
        self._chart_frame.pack(fill='both', expand=True)

        if self._canvas_widget:
            self._canvas_widget.get_tk_widget().destroy()

        fig, ax = plt.subplots(figsize=(9, 5), facecolor='#0d1117')
        idx = self.CHARTS.index(self._chart_var.get())
        chart_fns = [
            lambda a: Visualizer(self._filtered_df, EDAAnalyzer(self._filtered_df)).plot_survival_by_class(a),
            lambda a: Visualizer(self._filtered_df, EDAAnalyzer(self._filtered_df)).plot_survival_pie(a),
            lambda a: Visualizer(self._filtered_df, EDAAnalyzer(self._filtered_df)).plot_age_histogram(a),
            lambda a: Visualizer(self._filtered_df, EDAAnalyzer(self._filtered_df)).plot_survival_by_sex(a),
            lambda a: Visualizer(self._filtered_df, EDAAnalyzer(self._filtered_df)).plot_age_vs_fare(a),
            lambda a: Visualizer(self._filtered_df, EDAAnalyzer(self._filtered_df)).plot_fare_trend_by_age_group(a),
            lambda a: Visualizer(self._filtered_df, EDAAnalyzer(self._filtered_df)).plot_correlation_heatmap(a),
            lambda a: Visualizer(self._filtered_df, EDAAnalyzer(self._filtered_df)).plot_survival_by_agegroup(a),
        ]
        chart_fns[idx](ax)
        fig.tight_layout()

        self._canvas_widget = FigureCanvasTkAgg(fig, master=self._chart_frame)
        self._canvas_widget.draw()
        self._canvas_widget.get_tk_widget().pack(fill='both', expand=True)
        self._status.set(f"✅  Rendered: Chart {idx+1}")

    def _apply_filter(self):
        df = self._df.copy()
        if self._sex_var.get() != 'All':
            df = df[df['Sex'] == self._sex_var.get()]
        if self._pclass_var.get() != 'All':
            df = df[df['Pclass'].astype(str) == self._pclass_var.get()]
        self._filtered_df = df
        self._status.set(f"🔎  Filter applied — {len(df):,} rows shown.")

    def _reset_filter(self):
        self._filtered_df = self._df.copy()
        self._sex_var.set('All')
        self._pclass_var.set('All')
        self._status.set(f"↩️  Filter reset — {len(self._df):,} rows.")

    def _export_csv(self):
        path = filedialog.asksaveasfilename(
            defaultextension='.csv',
            filetypes=[("CSV files","*.csv")],
            initialfile='titanic_filtered.csv'
        )
        if path:
            self._filtered_df.to_csv(path, index=False)
            messagebox.showinfo("Export", f"✅  Saved {len(self._filtered_df):,} rows to:\n{path}")
            self._status.set(f"💾  Exported → {path.split('/')[-1]}")

    def run(self):
        self._root.mainloop()


# ── Launch the GUI ─────────────────────────────────────────────────────────────
def launch_gui(df):
    try:
        root = tk.Tk()
        app  = TitanicGUI(root, df)
        print("✅  GUI launched — close the window to continue the notebook.")
        app.run()
    except Exception as e:
        if 'display' in str(e).lower() or 'tcl' in str(e).lower() or 'no display' in str(e).lower():
            print("⚠️  No graphical display detected (headless environment).")
            print("   → Run this notebook locally to use the Tkinter GUI.")
            print("   → All analysis and charts are still fully available above.")
        else:
            raise

launch_gui(df_clean)

"""## 10. 📝 Conclusion

This project delivered a **complete, production-quality Python AI data analysis application** on the Titanic dataset:

### ✅ Requirements Met

| Requirement | Status | Detail |
|---|---|---|
| Data Loading | ✅ | CSV from URL + fallback synthetic data |
| Missing Value Handling | ✅ | Stratified median imputation for Age, mode for Embarked |
| Duplicate Removal | ✅ | `drop_duplicates()` with logging |
| Type Conversion | ✅ | Pclass→category, Sex encoding, float rounding |
| Feature Engineering | ✅ | FamilySize, IsAlone, FarePerPerson, AgeGroup |
| Outlier Handling | ✅ | 99th-percentile capping on Fare |
| 5+ Visualizations | ✅ | **8 charts** (bar×3, pie, histogram, scatter, line, heatmap) |
| OOP (≥3 classes) | ✅ | **4 classes** with constructors, encapsulation, methods |
| GUI | ✅ | Full Tkinter app with load, filter, chart select, export |
| CSV Export | 🎁 | Bonus feature |
| Correlation Heatmap | 🎁 | Bonus feature |
| Search / Filter | 🎁 | Bonus feature by Sex & Pclass |

### 🔑 Key Insights
- **38.4%** of passengers survived overall
- **Women** had a ~74% survival rate vs ~19% for men ("women and children first")
- **1st-class** passengers had a ~63% survival rate vs ~24% for 3rd-class
- **Children** (< 12) had the highest relative survival rate
- Fare and Pclass are strongly negatively correlated (−0.55)

---
*Developed by AbuTalha Saleem (F2024376221) — Programming for AI, Fall 2026*

"""